image: node:8.11.4

before_script:
    - npm prune
    - npm update -q  
    
stages:
  - install
  - build
  - test
  - deploy
  
install_npm_modules:
    stage: install
    script: npm install
  
test_client:
    stage: test
    script: npm run test
      
build_client:
    stage: build
    script: npm run build
    
build_image:
    stage: deploy
    script: apt-get install docker
     