image: docker:latest

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  NODEJS_VERSION: 8.12.0
  NPM_VERSION=6.4.1
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules
  - build


before_script:
    - apk --no-cache add curl 
    - apk add --update nodejs=$NODEJS_VERSION nodejs-npm=$NPM_VERSION git
  
stages:
  - install
  - build
  - test
  - deploy
  
install_npm_modules:
    stage: install
    script: 
        - npm install
        - npm install --force git+https://github.com/erssebaggala/layout.git
  
test_client:
    stage: test
    script: 
#        - npm run test
        - echo "Run tests"

      
build_client:
    stage: build
    script: 
        - export NODE_OPTIONS=--max_old_space_size=4096
        - unset CI
        - npm run build
    
build_image:
    stage: deploy
    script: 
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
        - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
        - docker push $CONTAINER_IMAGE:latest
     